### ISSUE TITLE
Add option to stream a list timeline

### ISSUE THREAD

**Issue by louis-clotman** [sferik/x-cli#162]
t timeline [USER/]LIST stream

... would be nice.

**Comment by zhao-ji** [comment]
@jrbalderrama  goog job! but if the member of list is changed, we should get the list again, and restart the StreamFilter.

**Comment by jrbalderrama** [comment]
Are the flags  --no-replies and --no-retweets still working?

**Comment by zhao-ji** [comment]
let me have a look at
