### ISSUE TITLE
It does not work with proxies (by exporting http_proxy)

### ISSUE THREAD

**Issue by fgielow** [sferik/x-cli#73]
Hello!

I am trying to use the t CLI with a proxy, exported through the http_proxy environment variable.
But if I export it with **$ export http_proxy=xxx.xxx.xxx.xxx:pppp**, it returns : 

`/usr/local/lib/ruby/1.9.1/uri/common.rb:176:in `split': bad URI(is not URI?): xxx.xxx.xxx.xxx:pppp (URI::InvalidURIError)
    from /usr/local/lib/ruby/1.9.1/uri/common.rb:211:in `parse'
    from /usr/local/lib/ruby/1.9.1/uri/common.rb:747:in `parse'
    from /usr/local/lib/ruby/1.9.1/uri/common.rb:994:in `URI'
    from /usr/local/lib/ruby/gems/1.9.1/gems/faraday-0.8.4/lib/faraday/connection.rb:169:in `URI'
    from /usr/local/lib/ruby/gems/1.9.1/gems/faraday-0.8.4/lib/faraday/connection.rb:160:in `proxy'
    from /usr/local/lib/ruby/gems/1.9.1/gems/faraday-0.8.4/lib/faraday/connection.rb:46:in `initialize'
    from /usr/local/lib/ruby/gems/1.9.1/gems/faraday-0.8.4/lib/faraday.rb:11:in `new'
    from /usr/local/lib/ruby/gems/1.9.1/gems/faraday-0.8.4/lib/faraday.rb:11:in `new'
    from /usr/local/lib/ruby/gems/1.9.1/gems/twitter-4.1.2/lib/twitter/client.rb:55:in `connection'
    from /usr/local/lib/ruby/gems/1.9.1/gems/twitter-4.1.2/lib/twitter/client.rb:70:in `request'
    from /usr/local/lib/ruby/gems/1.9.1/gems/twitter-4.1.2/lib/twitter/client.rb:36:in `get'
    from /usr/local/lib/ruby/gems/1.9.1/gems/twitter-4.1.2/lib/twitter/api.rb:2348:in `object_from_response'
    from /usr/local/lib/ruby/gems/1.9.1/gems/twitter-4.1.2/lib/twitter/api.rb:2172:in `user'
    from /usr/local/lib/ruby/gems/1.9.1/gems/t-1.4.0/lib/t/cli.rb:782:in `whois'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thor-0.16.0/lib/thor/task.rb:27:in `run'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thor-0.16.0/lib/thor/invocation.rb:120:in `invoke_task'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thor-0.16.0/lib/thor.rb:275:in `dispatch'
    from /usr/local/lib/ruby/gems/1.9.1/gems/thor-0.16.0/lib/thor/base.rb:425:in `start'
    from /usr/local/lib/ruby/gems/1.9.1/gems/t-1.4.0/bin/t:13:in `<top (required)>'
    from /usr/local/bin/t:23:in `load'
    from /usr/local/bin/t:23:in `<main>'`

If I instead try to use **$ export http_proxy="http://xxx.xxx.xxx.xxx:pppp"**, it keeps frozen for a reasonable time, maybe 2 minutes, and finally responds `/usr/local/bin/t: end of file reached`.

I am not really experienced with ruby, hence I do not know if the error lies on the way "t" handles something there, or if there is any issue on others Gems upon which t relies on. From my feedback, does it like like t's issue?

Thanks very much! Great tool.

**Comment by anonnyj** [comment]
Ran into this problem too.

**Comment by anonnyj** [comment]
Ran into this problem too. Did you figure it out, fgielow? (sorry for the 5 year necromancy)
